# Generated by Django 4.1.6 on 2023-02-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_tutoringuser_is_tutor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringuser',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
