# Generated by Django 4.1.6 on 2023-03-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tutoringuser_is_tutor_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='tutoringuser',
            name='full_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutoringuser',
            name='major',
            field=models.CharField(choices=[('ECE', 'Electrical/Computer Engineering'), ('BME', 'Biomedical Engineering'), ('CS', 'Computer Science'), ('HIS', 'History'), ('PSY', 'Psychology'), ('PSY', 'Psychology')], default='NA', max_length=3),
            preserve_default=False,
        ),
    ]
