# Generated by Django 4.1.6 on 2023-03-19 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_tutorrequest_tutoringuser_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='request_tutor',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='request_user',
            field=models.CharField(default='N/A', max_length=50),
            preserve_default=False,
        ),
    ]
