# Generated by Django 4.1.6 on 2023-03-19 18:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tutorrequest_request_time_tutorrequest_request_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringuser',
            name='classes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['None'], size=None),
            preserve_default=False,
        ),
    ]
