# Generated by Django 4.1.6 on 2023-03-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_tutoringuser_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringuser',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
