# Generated by Django 4.1.6 on 2023-03-19 20:59

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_tutoringuser_pay_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringuser",
            name="is_virtual",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tutoringuser",
            name="locations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="NA", max_length=20),
                default=home.models.TutoringUser.get_default,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tutoringuser",
            name="classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="NA", max_length=50),
                default=home.models.TutoringUser.get_default,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="tutoringuser",
            name="pay_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
