# Generated by Django 4.1.6 on 2023-03-19 21:42

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_tutoringuser_is_virtual_tutoringuser_locations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutoringuser",
            name="Availability",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="NA", max_length=50),
                default=home.models.TutoringUser.get_default,
                size=None,
            ),
        ),
    ]
