# Generated by Django 4.1.6 on 2023-04-02 04:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tutoringuser_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorrequest',
            old_name='request_time',
            new_name='request_startTime',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='request_endTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
