# Generated by Django 4.1.6 on 2023-04-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_request_time_tutorrequest_request_starttime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutoringuser',
            old_name='Availability',
            new_name='availability',
        ),
    ]
