# Generated by Django 4.1.6 on 2023-04-12 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_tutorrequestaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorrequest',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='request_endTime',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='request_startTime',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='request_tutor',
        ),
        migrations.RemoveField(
            model_name='tutorrequest',
            name='request_user',
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='session_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorrequest',
            name='tutor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutoringuser',
            name='major',
            field=models.CharField(choices=[('ECE', 'Electrical/Computer Engineering'), ('BME', 'Biomedical Engineering'), ('CS', 'Computer Science'), ('HIS', 'History'), ('PSY', 'Psychology')], max_length=3),
        ),
        migrations.DeleteModel(
            name='TutorRequestAccount',
        ),
    ]
