# Generated by Django 4.1.6 on 2023-04-15 09:46

import django.contrib.postgres.fields
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_tutorrequest_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringuser',
            name='availability',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='NA', max_length=255), default=home.models.TutoringUser.get_default, size=None),
        ),
    ]
