# Generated by Django 4.1.6 on 2023-04-15 10:08

import django.contrib.postgres.fields
import django.core.serializers.json
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_tutoringuser_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringuser',
            name='tutorSession',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder), blank=True, default=home.models.TutoringUser.get_default, null=True, size=None),
        ),
    ]
