# Generated by Django 4.1.6 on 2023-04-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_tutoringuser_tutorsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
