# Generated by Django 4.1.6 on 2023-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_tutorrequest_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorrequest',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
