# Generated by Django 4.1.6 on 2023-04-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_tutorrequest_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorrequest',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
